### ISSUE TITLE
Better NPC not found error message

### ISSUE THREAD

**Issue by purrplingcat** [purrplingcat/PurrplingMod#101]
As a **mod developer**
I have to **better NPC not found message for csm initialization**
I should **don't resolve false bug reports and not to confuse players and content pack creators**

Don't throw an exception *Can't find NPC*, just log an error log message and skip affected CSM and don't load it. Unaffected companions must be successfully loaded and mod must have to works without restrictions (only missing NPC not to be added as companion and can't be recruited)

Suggested error message:

> Unable to initialize companion `<npc>`, because this NPC cannot be found in the game. Are you trying to add a custom NPC as a companion? Check the mod which adds this NPC into the game. Don't report this as a bug to NPC Adventures unless it's a vanilla game NPC.

**Comment by CallMeFoxie** [comment]
> Unable to initialize companion `<npc>`, because this NPC cannot be found in the game. Are you trying to add a custom NPC as a companion? Check the mod which adds this NPC into the game. Don't report this as a bug to NPC Adventures unless it's a vanilla game NPC.
