### ISSUE TITLE
[Feature request] New Personal Skill --> Blessed or Spiritualist

### ISSUE THREAD

**Issue by Caco-o-sapo** [purrplingcat/PurrplingMod#124]
I am suggesting a new personal skill, primary for Emily.
The skill could be called **Blessed or Spiritualist.**

It would be about how she is with Yoba and the spirits.
When you're about to die in mines or need a quick heal, you coud ask her to make an "pray" to Yoba and the spritis to save you two. And ocassionaly give you complete health or some random buff.

She would give you more luck in the mines or make some monsters be afraid of her because of her "pure" aura.

**Comment by purrplingcat** [comment]
For healing is here doctor personal skill.
