### ISSUE TITLE
[Feature request] Enter companions's house any time

### ISSUE THREAD

**Issue by purrplingcat** [purrplingcat/PurrplingMod#131]
**Is your feature request related to a problem? Please describe.**
Add a feature where you can enter an NPC's house at any time if they're following you.

**Describe the solution you'd like**
If you have recruited a companion you can enter their house any time without care if door is locked or not. Farmer can enter any time only current recruited companion's house. When companion dismiss, then farmer lost any time access to their house until recruit them again.

**Describe alternatives you've considered**
If this mean write lot of harmony patches, don't implement it, can be so messy. Otherwise is a good idea ang takes a sense to have it.

**Additional context**
Proposed by [ncirrus](https://www.nexusmods.com/users/84477543)

**Comment by purrplingcat** [comment]
Need analysis how to do it and if this feature needs harmony patching or not.

**Comment by almondlynx** [comment]
Actually you can do a little cheaty workaround to implement this
Temporarily patch maps instead of editing the code itself
No harmony required if done this way

**Comment by purrplingcat** [comment]
@almondlynx Can temporarily map patch broke something in game for other mods? Like TMX edits a map in the same position as mine, or other mods edit town map and the house door are no longer on the position of vanilla house door.

You can write draft code and test on it. I'll work on this ticket in future versions (not for 0.12.0) and I'll take some time for analyze this, but if somebody has an idea how to do it, I welcome any draft code and save time with analysis. Then I can release this feature earlier 😊
