### ISSUE TITLE
[BUG] Invalid IL code

### ISSUE THREAD

**Issue by thong637** [purrplingcat/PurrplingMod#154]
Android new Bug !
![Screenshot_20200722-102629](https://user-images.githubusercontent.com/68627598/88131358-ffb2cf00-cc06-11ea-9141-5562d123895a.jpg)

**Comment by purrplingcat** [comment]
Plese send me full smapi log via smapi.io/log

**Comment by thong637** [comment]
https://smapi.io/log/2fa53c1a6777408c949af62f5e24cc54

**Comment by purrplingcat** [comment]
I see you have installed broken mod FlyCam. Remove it and try it again.

**Comment by thong637** [comment]
I just deleted a lot of mods and it still fails!
Log:https://smapi.io/log/9d9e535839bb4994a60b690ccda30b2f

**Comment by thong637** [comment]
You can watch the video and see the NPC slash does not damage!
https://drive.google.com/file/d/10PzPcXLHFJTh90IaR0581hG1gJIUByr1/view?usp=drivesdk

**Comment by purrplingcat** [comment]
I have no idea why is it, it's in extension https://github.com/purrplingcat/PurrplingMod/blob/2e8da509b8a3d1aa389d5176f6dded88b98aac58/NpcAdventure/Utils/Extensions.cs#L50 but idk why and what concrete. I am not android developer, you can try clone NA and try play with it. I can't fix it because I don't understand.

**Comment by thong637** [comment]
<html>
<body>
<h1><B><I>From version 0.12.0 and above, the Mod has such error!</B></I></h1>
</body>
<p1>—<I>It seems that StardewValley.dll Android does not exist Boolean </p1><p2><a href="https://github.com/purrplingcat/PurrplingMod/blob/2e8da509b8a3d1aa389d5176f6dded88b98aac58/NpcAdventure/Utils/Helper.cs#L107 ">Game1.isRaining, Game1.isSnowing, Game1.isLightning, Game1.isDebrisWeather</a></p2>
</htmt>

**Comment by Caco-o-sapo** [comment]
@thong637 Strangely enough, I play the mod as normal and don't have such errors. There must be something else interfering.

**Comment by thong637** [comment]
At first, I took the NPC to slash monsters like <B>normal</B>.  But why when I create a new game, the NPC can not slash monsters anymore!

**Comment by Caco-o-sapo** [comment]
Well as I said. Something else is interfering with it. Since I play as normal in multiple saves. And the NPCs slash the monsters as normal and no errors happens.

**Comment by purrplingcat** [comment]
I officialy declare NPC Adventures as incompatible with Android since 0.13.0. all android issues will not be fixed, because I haven't knowledge and expireince to fix them.
