### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Caco-o-sapo** [purrplingcat/PurrplingMod#156]
Add a HasMod condition, so use different quests depending on what mod the player has.

**Comment by purrplingcat** [comment]
This is out of scope this mod. If you want to restrict which mod is loaded, use dependencies in SMAPI manifest.json. to define NPCs in CompanionDefinition file you always need installed dependant mod.

**Comment by Caco-o-sapo** [comment]
I don't want to restrict mod usage, I want to make different quests based on which mods are loaded. Like if I want to make a LostItem quest and there is mods that change the map that I'm using, I would use `HasMod` flag to change the place and other things dynamically without having to manage several different mods folders.

**Comment by purrplingcat** [comment]
Then you are add this proposal to bad project. This is NPC Adventures repo, not QF.

**Comment by Caco-o-sapo** [comment]
Oh crap GitHub app... Leaded me to the wrong repo...
