### ISSUE TITLE
[BUG] Sprite hovering like fog in mines

### ISSUE THREAD

**Issue by Khataro** [purrplingcat/PurrplingMod#158]
I get a strange bug when i enter level 31 and deeper in the mines. The ask_to_follow sprite is hovering like fog all over the place. Deeper down the mines its gone, happens only in this dark themed part of the mines so far. Even happening if i remove the (SVE) Stardew Valley Expanded Companions - NPC Adventures-unofficial.1-mardrest mod. Any ideas? https://smapi.io/log/1a33b0beb8864deaaee4abf21b6e9bfa

**Comment by purrplingcat** [comment]
You can disable that cursor in config.json. Open config file and fin key `UseAsk2Follow` and set it to false. The speech cursor will be used for ask to follow.
