### ISSUE TITLE
Dialogue idea for more vanilla NPCs

### ISSUE THREAD

**Issue by Kayayak** [purrplingcat/PurrplingMod#160]
**Some dialogue Idea for some vanilla non-datable npc**
This is just a few very simple ideas. For more inspiration! I just thought it was better to leave it than forget it.
ideas mainly based on their professional characteristics. Adults teach new young farmers the wisdom of their lives.

**Robin** : I'd like to do a logging with Robin. Robin teaches us how to find good trees, old mysterious trees(Some trees should never be cut down.), mushrooms in the woods, deer and wildlife. Hard and strong wood, soft but beautiful wood, etc. She might mention Leah about carving wood.

**Caroline** : She was an adventurous girl. (Abigail would look like her.) She likes to explore mysterious places in the forest. When she is tired of shop work and family work, she may find a special place to spend a quiet time. She likes gardening, so she can tell stories about flowers and mysterious trees.

**Clint** : He is very introverted, but he needs to go to the mine because he is a blacksmith. It is difficult to explore a dark, monster-filled mine alone. He can ask the farmer for help. He can tell about finding quality ore, rescuing small pieces of ore from river/sea, and idea about making some craft.

**Demetrius**: Collecting samples for his research. He can talk about some of the scientific information of seasonal crop/forage.
**Marnie**: Collect cave carrots or grass for her livestock! she can talk about a variety of wild animals.
**Willy** : I'd like to invite him to fish in a cave.
**Linus**: it will be peaceful time to collecting forage with him and talking about nature.

**Comment by purrplingcat** [comment]
These characters are not companions. I can't add companion dialogues for them. Not all vanilla NPCs are companions. If you want add non-datable NPCs, I recommend add them via custom content pack.
