### ISSUE TITLE
Intallation error becausea error report in "manifest.json"[BUG]

### ISSUE THREAD

**Issue by FOXTwT** [purrplingcat/PurrplingMod#165]
**Describe the bug**
When i'd tryed install the mod the voxel manager report a error in "manifest.json" arquive and cancel the installation.

**To Reproduce**
1. Download the mod arquive, for the the voxel manager or navegator.
2. Try to install the mod.
3. See error.

**Expected behavior**
The manager reporte an error.

**Screenshots**
![Captura de tela 2020-12-05 135426](https://user-images.githubusercontent.com/74617898/101258489-8a512200-3701-11eb-8021-c0d3c19ac928.png)
Trying installation

![Captura de tela 2020-12-05 135454](https://user-images.githubusercontent.com/74617898/101258517-c1273800-3701-11eb-9c06-ca1e4204715d.png)
Installation error report

**Desktop:**
 - OS: [Windows 10]
 - SDV version [1.4.5]
 - SMAPI version [3.7.6]

 - Version [0.15.0]

**Additional context**

**Comment by purrplingcat** [comment]
Not a problem of the mod. Contact vortex developer
