### ISSUE TITLE
[Suggestion] New Personal Skills + Magic/Cooking Skill

### ISSUE THREAD

**Issue by somohexuals** [purrplingcat/PurrplingMod#91]
[Magic](https://www.nexusmods.com/stardewvalley/mods/2007)
- This mod lets you cast spells by using a Mana resource bar. Casting spells grants experience toward the Magic skill. Your Mana regenerates over time based on your Magic level. 
Use:
- Can be used to add personal skills like "Mage" and etc.
- Ex: Rasmodius (if anyone wanted to make him a companion) could grant +2 Magic (allowing you to cast spells more frequently with him).

[Cooking Skill](https://www.nexusmods.com/stardewvalley/mods/522)
- This mod adds a Cooking skill to the game. Creating cooked food grants skill exp. You have a chance to create higher quality meals (silver/gold/iridium) based on your Cooking skill level.
Use:
- Penny's buff could be changed from +3 Farming to +3 Cooking. This fits thematically and would make her more unique as Shane also gives +3 Farming.

-----------------------------------------------------------------------------------------------
Ideas for Personal Skills:

1. Mage
- Cannot fight with a weapon (unless also a Fighter/Warrior/etc)
- Basic attack: Normal damage "Arcane Bolt" tracking projectile
- Occasional special attack: Fireball projectile that travels in a line, exploding when it hits an enemy 
- Will cast "Illuminate" (granting them a light radius) when in mines or at night
* Your companion's damage and light radius could increase based on your Magic skill level (like how Warriors scale with your Combat level).

2. Cleric
- Can fight with a weapon, but deals significantly less damage than a Fighter/Warrior/etc.
- Basic attack: Normal weapon attack.
- Occasional special attack: Fires a projectile that reduces a monster's defense (like Shadow Shamans).
- Can cast "Restore/Heal" to heal you during combat if your HP drops below a certain % (like Shadow Shamans).
- Will not heal you on demand out of combat like a Doctor.
* Your companion's healing and debuff strength could increase based on your Magic skill level.

3. Summoner
- Cannot fight with a weapon (unless also a Fighter/Warrior/etc)
- Basic attack: Normal damage "Arcane Bolt" tracking projectile
- Occasional special attack: "Entangle" roots an enemy in place
- Will cast "Summon Familiar" (giving them a pet Slime or Bat that fights enemies) when in mines or at night
* Your companion's damage, root duration, and pet type (Normal/Frost/Lava/Iridium Bat) or (Green/Blue/Red/Purple Slime) could increase based on your Magic skill level.

4. Ranger
- Will only fight using a Slingshot.
- Will use the first item in their inventory as ammo (if it can be used as ammo for a Slingshot).
- Cannot attack unless they have ammo. Will not use quality items as ammo.
- Basic attack: Normal projectile attack.
- Occasional special attack: Uses explosive projectile attack (even if they don't have Explosive Ammo).
- The value of the item used as ammo will increase their basic and special attack damage (just like how Slingshots work for players)
* Your companion's damage and slingshot could upgrade based on your Combat level (just like a Warrior does with swords).

I know this is a LOT so I have no expectations that this will happen even remotely soon. I just like to theorycraft and wanted to throw this out there.

**Comment by purrplingcat** [comment]
I don't understand why you linekd existing mods. NA is incompatible amd crashes with this mods?

Mage skill is in roadmap. See issue #59 

Please describe more what you mean. I recommend use issue templates, like feature request. It's a template which can help you to describe your concept.

**Comment by somohexuals** [comment]
I apologize, I don't know how I overlooked the template. :(

**Is your feature request related to a problem? Please describe.**
Companions are only able to fight with melee weapons and Penny's buff could be made more unique as it's the same as Shane's.

**Describe the solution you'd like**
Integrate the Magic mod so companions can benefit from the player's Magic skill level, provide buffs to the Magic skill, and use spells with that mod. Integrate the Cooking Skill mod so companions (namely Penny) can provide buffs to the Cooking skill.

**Describe alternatives you've considered**
Mage, Cleric, Summoner, and Ranger are Personal Skills that could be added. Mage, Cleric, and Summoner would work with the Magic mod.

**Additional context**
I linked the Magic and Cooking Skill mods so you'd be able to quickly see what they're about and if you're interested in integrating them/allowing compatibility. They have no issues with NA.

Issue #59  talks about a theoretical magic system, I submitted a suggestion for the Magic mod because it's an already existing magic system that you could use or build upon, rather than creating one from scratch. It has out-of-combat type spells and combat spells so it would cover what #59 suggests and more.

The personal skills are largely intended for upcoming Stardew Valley Expanded NPC's (in the next update Rasmodius is being fleshed out as a character and his mage apprentice, Morgan, is being added to the game). These two and many other NPC's from SVE are known magic users so having them fight with a sword would be odd to me. 
Like #59 mentions, there are also NPC's from the base game that could use these personal skills. Rasmodius, Abigail, Dwarf, and Krobus come to mind. 
It could also be useful for future content packs if someone wanted to add some background to certain vanilla characters (Ex: If someone adds dialogue to Caroline indicating she learned a little magic from her time with Rasmodius, she could use a few spells as a companion).

**Comment by purrplingcat** [comment]
Closed due to aborted development of mod.
